### PR TITLE
add new steps

### PR DESCRIPTION
**Pull request by tshedor**
Hey @jonsamwell, sorry for dumping this big PR on your doorstep. We're huge fans of this package at Greenbits and we wanted to contribute our generic steps back to the community.

I understand that more code means more maintenance, so I'd be happy to remove some steps if you find them not universally applicable or not worth maintaining in the core package. I'd also be happy to change any of the API to make it more in line with your vision. 

The step class names are not prefixed with a Cucumber keyword because they can be used with any Cucumber keyword (e.g. instead of `GivenISwipeOnKey` it's just `SwipeOnKey`).

### CODE REVIEW

**Comment by jonsamwell** [comment]
Hi @tshedor Thanks for this it looks good - I'll have some time tomorrow and go over it.  Really appreciate the pull request and glad you are finding the package useful!

**Comment by jonsamwell** [comment]
@tshedor I'm really really really sorry I have not merged this yet.  I have been so busy.  I've got some free time tomorrow so I'll get this and the Slack reporter merged in!

**Comment by tshedor** [comment]
@jonsamwell no worries mate, I know how unrewarding and time consuming open source maintenance can be. Holler if I can clean up or standardize either of these PRs.

**Comment by jonsamwell** [comment]
@tshedor sorry for the delay here!  I've updated the new steps into the new function base step implementation format as I think the library should favour that now as it is a bit simpler than create an entire class per step.

**Pull request merged**
