### PR TITLE
Add ability to consume `dart-define` args

### PR DESCRIPTION
**Pull request by Pholey**
Noticed there was no way to configure this; if there's any changes needed lmk

### CODE REVIEW

**Comment by Antoniozinchenko** [comment]
I think this PR needs Readme description.
Great work!

**Comment by jonsamwell** [comment]
Thanks for this, I'll get this merged in this week!

**Comment by tshedor** [comment]
@jonsamwell do you think you could merge and release this before any null safety work? It'd be a huge help.

**Comment by jonsamwell** [comment]
I'll get this release tomorrow

**Pull request merged**
