### PR TITLE
Add optional build flavor and device target id

### PR DESCRIPTION
**Pull request by iqbalmineraltown**
I'm adding optional build flavor and device id arguments

### CODE REVIEW

**Comment by jonsamwell** [comment]
@iqbalmineraltown this is awesome thank you for adding this it is a great addition.  Could I trouble you to add a bit to the readme for it?

**Comment by jonsamwell** [comment]
I have never used build flavors so I'll be learning here too!

**Comment by iqbalmineraltown** [comment]
oops I forgot the readme

is this sufficient?

**Comment by jonsamwell** [comment]
@iqbalmineraltown amazing work thank you!  I really appreciate help with this!  I'll merge it in now and I'll do a release tomorrow as it's quite late now.

**Pull request merged**
