### PR TITLE
Added table data for reporters to use

### PR DESCRIPTION
**Pull request by Holloweye**
I created my own json reporter which requires the step's table data to be more complete. I can add the json reporter as a pull request later if you want. The json file can be used with this tool: https://www.npmjs.com/package/cucumber-html-reporter , to generate awesome looking html reports.

### CODE REVIEW

**Comment by jonsamwell** [comment]
@Holloweye many thanks for this and yes please do a PR for the JSON reporter.  Could you updated the tests as I think they might fail because of the new call signature.

**Comment by Holloweye** [comment]
I ran the tests before, they were a green for me

**Comment by jonsamwell** [comment]
@Holloweye great update the PR and I'll merge it in.

**Comment by jonsamwell** [comment]
Thanks for the PR awesome work!

**Pull request merged**
