### PR TITLE
Fixed an issue with code generation.

### PR DESCRIPTION
**Pull request by AFASbart**
Fixed issue #165

### CODE REVIEW

**Comment by BartVerm779** [comment]
@jonsamwell can you take a look at this?

**Comment by jonsamwell** [comment]
Did you see my code review comment yesterday?

**Comment by AFASbart** [comment]
I do not see any comments?

**Comment by jonsamwell** [comment]
Odd! It just said change the != '' to . isNotEmpty

Do that and I'll approve and merge it in later

**Comment by AFASbart** [comment]
should be updated

**Comment by jonsamwell** [comment]
Thanks!

**Comment by jonsamwell** [comment]
@AFASbart I'll get this published tomorrow I've ran out of time this evening

**Comment by AFASbart** [comment]
@jonsamwell Can you create the 3.0.0-rc.8 version for me with this change?

**Comment by jonsamwell** [comment]
Published!

**Pull request merged**
