### PR TITLE
Path in report (RunnableDebugInfo update)

### PR DESCRIPTION
**Pull request by AFASbart**
In the reports the path is empty, this is because the path that is being fed, is just an empty string. I have replaced this with the actual path.

### CODE REVIEW

**Comment by AFASbart** [comment]
This needs a new version of the dart_gherkin / gherkin package. I have also made a pull request there @jonsamwell

**Comment by AFASbart** [comment]
Can you have a look at this @jonsamwell ? Would be great if implemented!

**Comment by AFASbart** [comment]
Hey @jonsamwell , I know you have some time constraints, is it possible for you to give me permission to do merge requests etc, in the dart_gherkin package? Then I can also approve this merge request!

**Comment by jonsamwell** [comment]
> Hey @jonsamwell , I know you have some time constraints, is it possible for you to give me permission to do merge requests etc, in the dart_gherkin package? Then I can also approve this merge request!

Sure

**Comment by jonsamwell** [comment]
Closing as we have as this is in the dart-3.0 branch

**Pull request closed without merging**
