### PR TITLE
Guarded function conflict resolve

### PR DESCRIPTION
**Pull request by veesmana**
Hi @jonsamwell
I have the same issue for this problem (https://github.com/jonsamwell/flutter_gherkin/issues/198)
After your comment I started look for solution how to fix it
And I found solution witch work great for me and I want to share it with you maybe this can be helpful for your package.
Without the pumpAndSettle() some steps don't work as well. But in the most cases we can work well without this method.
And I skip it from runner to minimize risk to get the conflicts.

### CODE REVIEW

**Comment by AFASbart** [comment]
I think removing the pumpAndSettle() function is dangerous, because we of course want to wait before the next action. I will take a look at how the app then functions later this week.

**Comment by jonsamwell** [comment]
@AFASbart I was thinking we could make the use of implicit pumpAnSettle() calls dependent on an enum value the user can set in the configuration.  This way we could handle both scenarios.  Or even allow the user to supply their own "Wait After Action" code?

**Comment by AFASbart** [comment]
I think the last option is the best option, because then you can do it per step and also disable if you want to.

**Comment by jonsamwell** [comment]
Agree, so we can just default it to pump and settle and the user can do what they want if needed

**Comment by Ekhart86** [comment]
Please accept these changes, I really need them, I cannot write tests properly because of pumpAndSettle() method which is inside of startApp() method. I have an endless animation on the start screen.

**Comment by AFASbart** [comment]
I will look at this tonight (EU west time)

**Comment by Ekhart86** [comment]
Guys I'm still waiting for you to release a new version of the package) I hope it will happen soon)

**Comment by AFASbart** [comment]
And I still require @jonsamwell to publish the new version of the dart package :)

**Comment by AFASbart** [comment]
I currently have added the option for this pumpAndSettle to be switchable. If @jonsamwell pushes the new version, you can update this PR and then we can merge it. The new option in the configuration is useWaiters

**Comment by jonsamwell** [comment]
The dart_gherkin package has been published.  Sorry for the delay

**Comment by Ekhart86** [comment]
Great news! Thanks! This means that in the near future we can expect an update of the flutter_gherkin package too?

**Comment by jonsamwell** [comment]
@Ekhart86 yep we can get a release out tomorrow.  @AFASbart do you need to do anything for the release?

**Comment by AFASbart** [comment]
> @Ekhart86 yep we can get a release out tomorrow. @AFASbart do you need to do anything for the release?

I need a lot, luckily I am free this afternoon (Amsterdam time) so I probably have time to fix things. The dart_gherkin package has a whole new way of working and it was a breaking change. This means that we need to rework parts of flutter_gherkin (and that the new update will also be breaking)

**Comment by AFASbart** [comment]
Furthermore, this PR needs to be updated with conditional removals. (Configuration.useWaiters)

**Comment by jonsamwell** [comment]
@AFASbart I have time tomorrow to so let me know where you get up to.  We should think about pull the `integration_test__package_support` branch out of RC soon

**Comment by jonsamwell** [comment]
@AFASbart I can do the `useWaiters` work tomorrow

**Comment by AFASbart** [comment]
This latest addition will bring the package to a pretty stable and good replacement of the previous version (if it is up to me)

**Comment by jonsamwell** [comment]
Yeah agree, lets get this next release out of the way then push if to master afterwards

**Comment by jonsamwell** [comment]
Fixed in 3.0,0-rc-11

**Pull request closed without merging**
